services:
  pgadmin: 
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80

  pgdatabase:
    image: postgres:13
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/abbythecat27/my-de-zoomcamp/1_homework/green_taxi_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432